name: CD Netlify V2

on:
  push:
    branches:
      - netlify-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test 

      — name: “Deployed site” 
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}

      
      

      # - name: Install Netlify
      #   run: npm install netlify-cli@17.10.1 -g

      # - name: Install Dependencies
      #   run: npm ci

      # - name: Build for Netlify
      #   run: npm run build

      # - name: Deploy to Netlify
      #   id: netlify_deploy
      #   run: |
      #     netlify deploy \
      #       --dir dist \
      #       --site ${{ secrets.NETLIFY_SITE_ID }} \
      #       --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}

      # - name: Deploy to Netlify
      #   uses: netlify/actions/cli@master
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   with:
      #     args: deploy --dir=public --functions=functions --prod
